# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_SPI=y
CONFIG_LS0XX=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_LV_Z_VDB_SIZE=64
CONFIG_LV_DPI_DEF=145
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# --- ZMK STUDIO CONFIG ---
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable USB communication for Studio
# CONFIG_ZMK_STUDIO_TRANSPORT_USB=y

# DISABLE UART communication (Crucial for Trackpad)
CONFIG_ZMK_STUDIO_TRANSPORT_UART=n
