# Force disable display for the right side to prevent build errors
CONFIG_ZMK_DISPLAY=n
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=n
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# (Optional) Ensure Widgets are off
CONFIG_ZMK_WIDGET_LAYER_STATUS=n
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
